import { createClient } from '@supabase/supabase-js'
import Link from 'next/link'
import styles from './share.module.css'

const BLOCKS = [
  { id: 'decisions', label: 'Decisions',       color: 'spark'  },
  { id: 'actions',   label: 'Action Items',    color: 'ember'  },
  { id: 'questions', label: 'Open Questions',  color: 'fog'    },
  { id: 'risks',     label: 'Risks',           color: 'danger' },
  { id: 'email',     label: 'Follow-up Email', color: 'paper'  },
  { id: 'slack',     label: 'Slack Message',   color: 'paper'  },
  { id: 'agenda',    label: 'Next Agenda',     color: 'spark'  },
]

async function getMeeting(token: string) {
  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  )
  const { data } = await supabase
    .from('meetings')
    .select('title, created_at, pack, lang')
    .eq('share_token', token)
    .single()
  return data
}

export default async function SharePage({ params }: { params: { token: string } }) {
  const meeting = await getMeeting(params.token)

  if (!meeting) return (
    <div className={styles.notFound}>
      <div className={styles.notFoundLabel}>Pack not found</div>
      <Link href="/" className={styles.notFoundLink}>← MeetingFlash</Link>
    </div>
  )

  return (
    <div className={styles.page}>
      <nav className={styles.nav}>
        <Link href="/" className={styles.logo}>
          <img src="/logo.png" alt="" className={styles.logoMark} />
          MeetingFlash
        </Link>
        <div className={styles.navBadge}>Shared pack · Read only</div>
      </nav>

      <div className={styles.content} style={{ paddingBottom: 120 }}>
        <div className={styles.header}>
          <div className={styles.meta}>
            <span>{new Date(meeting.created_at).toLocaleDateString('en-GB', { day:'numeric', month:'long', year:'numeric' })}</span>
            <span className={styles.metaDot}>·</span>
            <span>{meeting.lang}</span>
          </div>
          <h1 className={styles.title}>{meeting.title}</h1>
        </div>

        <div className={styles.blocks}>
          {BLOCKS.map((block, i) => (
            <div
              key={block.id}
              className={`${styles.block} ${styles[`block_${block.color}`]}`}
              style={{ animationDelay: `${i * 0.06}s` }}
            >
              <div className={styles.blockHead}>
                <div className={styles.blockType}>
                  <div className={`${styles.blockDot} ${styles[`dot_${block.color}`]}`}/>
                  <span className={`${styles.blockLabel} ${styles[`label_${block.color}`]}`}>
                    {block.label}
                  </span>
                </div>
              </div>
              <div className={styles.blockContent}>
                {meeting.pack[block.id] || '—'}
              </div>
            </div>
          ))}
        </div>

        <div className={styles.footer}>
          <p>Generated by MeetingFlash</p>
          <Link href="/signup" className={styles.footerCta}>
            Create your free account →
          </Link>
        </div>
      </div>

      {/* STICKY BANNER */}
      <div className={styles.stickyBanner}>
        <div className={styles.stickyBannerLeft}>
          <span className={styles.stickyBannerTitle}>Turn your own meeting notes into an Execution Pack.</span>
          <span className={styles.stickyBannerSub}>5 free packs per month. No credit card.</span>
        </div>
        <Link href="/app" className={styles.stickyBannerCta}>Try free →</Link>
      </div>
    </div>
  )
}