import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { Resend } from 'resend'
import { buildFlashPrompt, generatePack, MAX_INPUT_CHARS, MIN_INPUT_CHARS, type Pack } from '@/lib/flashCore'
import { verifySvixSignature, extractInboundToken, cleanEmailBody } from '@/lib/inboundEmail'

// Email → Execution Pack ingestion.
//
// Flow: the user emails their raw meeting notes to their private address
// (flash+<token>@inbound.meetingflash.work), Resend's inbound webhook posts
// the parsed email here, we generate the pack, save it, and email it back.
// No browser, no login — notes typed on a phone during the meeting become a
// finished pack in the user's inbox.
//
// SETUP REQUIRED (one-time, see CLAUDE.md):
//   1. Resend → Domains → add `inbound.meetingflash.work` + its MX record
//   2. Resend → Webhooks → point `email.received` at /api/email/inbound
//   3. Set RESEND_INBOUND_SECRET (the whsec_… signing secret) in Vercel
//
// Identity comes from the token in the recipient address, never from the
// From header — that header is trivially spoofable.

export const maxDuration = 60

const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://www.meetingflash.work'

const esc = (s: string) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

function senderAddress(from: unknown): string | null {
  if (typeof from !== 'string') return null
  const angle = from.match(/<([^>]+)>/)
  const addr = (angle ? angle[1] : from).trim()
  return addr.includes('@') ? addr : null
}

/** Plain-text notice (quota hit, notes too short, …). */
async function replyNotice(resend: Resend, to: string, subject: string, message: string, cta?: { label: string; url: string }) {
  await resend.emails.send({
    from: 'MeetingFlash <hello@meetingflash.work>',
    to,
    subject,
    html: `
<div style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;max-width:520px;color:#101827;line-height:1.6">
  <p style="font-size:15px">${esc(message)}</p>
  ${cta ? `<p><a href="${cta.url}" style="display:inline-block;background:#2E62FF;color:#fff;padding:11px 22px;border-radius:8px;text-decoration:none;font-size:14px;font-weight:600">${esc(cta.label)}</a></p>` : ''}
  <p style="font-size:12px;color:#4C5A73;border-top:1px solid #e3e7f0;padding-top:14px;margin-top:22px">MeetingFlash · you received this because you emailed your private ingest address.</p>
</div>`,
  }).catch(() => {})
}

/** The finished pack, formatted for the inbox. */
async function replyWithPack(resend: Resend, to: string, pack: Pack, meetingId: string | null) {
  const packUrl = meetingId ? `${APP_URL}/dashboard/pack/${meetingId}` : `${APP_URL}/dashboard`
  const block = (label: string, body?: string) =>
    body && body.trim()
      ? `<h3 style="font-size:13px;letter-spacing:0.08em;text-transform:uppercase;color:#4C5A73;margin:26px 0 8px">${esc(label)}</h3>
         <div style="font-size:14px;white-space:pre-wrap;color:#101827">${esc(body.trim())}</div>`
      : ''

  await resend.emails.send({
    from: 'MeetingFlash <hello@meetingflash.work>',
    to,
    subject: `⚡ ${pack.title || 'Your Execution Pack'}`,
    html: `
<div style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;max-width:620px;color:#101827;line-height:1.6">
  <p style="font-size:12px;letter-spacing:0.1em;text-transform:uppercase;color:#4C5A73;margin-bottom:4px">Execution Pack</p>
  <h1 style="font-size:22px;margin:0 0 18px">${esc(pack.title || 'Untitled meeting')}</h1>
  ${pack.snapshot ? `<div style="background:#EDF2FF;border:1px solid rgba(46,98,255,0.25);border-radius:12px;padding:16px;font-size:14px">${esc(pack.snapshot)}</div>` : ''}
  ${block('Decisions', pack.decisions)}
  ${block('Action items', pack.actions)}
  ${block('Open questions', pack.questions)}
  ${block('Risks', pack.risks)}
  ${block('Follow-up email', pack.email)}
  ${block('Slack message', pack.slack)}
  ${block('Next agenda', pack.agenda)}
  <p style="margin:30px 0 0">
    <a href="${packUrl}" style="display:inline-block;background:#2E62FF;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-size:14px;font-weight:600">Open the full pack</a>
  </p>
  <p style="font-size:12px;color:#4C5A73;border-top:1px solid #e3e7f0;padding-top:14px;margin-top:26px">
    Generated by MeetingFlash from the notes you emailed in.
  </p>
</div>`,
  }).catch(() => {})
}

export async function POST(req: NextRequest) {
  const secret = process.env.RESEND_INBOUND_SECRET
  const body = await req.text()

  // Signature is mandatory in production: without it, anyone who discovers
  // this URL could forge inbound mail and spend the account's AI budget.
  if (!secret) {
    console.error('inbound: RESEND_INBOUND_SECRET not configured')
    return NextResponse.json({ error: 'Not configured' }, { status: 500 })
  }
  const signatureOk = verifySvixSignature({
    body,
    id: req.headers.get('svix-id'),
    timestamp: req.headers.get('svix-timestamp'),
    signature: req.headers.get('svix-signature'),
    secret,
  })
  if (!signatureOk) {
    return NextResponse.json({ error: 'Invalid signature' }, { status: 401 })
  }

  let payload: { type?: string; data?: Record<string, unknown> }
  try {
    payload = JSON.parse(body)
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  const data = payload.data ?? {}
  const token = extractInboundToken(data.to)
  const replyTo = senderAddress(data.from)

  // From here on we answer 200 for anything we've handled — a non-2xx would
  // make Resend retry an email that will never succeed.
  if (!token) return NextResponse.json({ ok: true, skipped: 'no token in recipient' })

  const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null

  const admin = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  )

  const { data: profile } = await admin
    .from('profiles')
    .select('id, email, plan, uses_this_month, default_lang, default_style')
    .eq('inbound_token', token)
    .single()

  if (!profile) {
    if (resend && replyTo) {
      await replyNotice(resend, replyTo, 'That MeetingFlash address is not active',
        'We could not match that address to an account. Check your personal ingest address in Settings and try again.',
        { label: 'Open Settings', url: `${APP_URL}/dashboard/settings` })
    }
    return NextResponse.json({ ok: true, skipped: 'unknown token' })
  }

  // Free plan quota — same rule as the web app.
  if (profile.plan === 'free' && (profile.uses_this_month ?? 0) >= 5) {
    if (resend && replyTo) {
      await replyNotice(resend, replyTo, 'You have used all 5 free packs this month',
        'Your free packs reset on the 1st. Upgrade to Pro for unlimited Execution Packs.',
        { label: 'See plans', url: `${APP_URL}/pricing` })
    }
    return NextResponse.json({ ok: true, skipped: 'quota reached' })
  }

  // Prefer the plain-text part; fall back to a crude strip of the HTML one.
  const rawText = typeof data.text === 'string' && data.text.trim()
    ? data.text
    : typeof data.html === 'string'
      ? data.html.replace(/<[^>]+>/g, ' ')
      : ''
  const notes = cleanEmailBody(rawText).slice(0, MAX_INPUT_CHARS)

  if (notes.length < MIN_INPUT_CHARS) {
    if (resend && replyTo) {
      await replyNotice(resend, replyTo, 'Those notes were too short to flash',
        'We need a bit more to work with — send the meeting notes in the body of the email (about 40 characters minimum).')
    }
    return NextResponse.json({ ok: true, skipped: 'body too short' })
  }

  // Free plan is English-only, exactly like the in-app language gate.
  const lang = profile.plan === 'free' ? 'EN' : (profile.default_lang || 'EN')
  const style = profile.default_style || 'Concise'

  let pack: Pack
  try {
    pack = await generatePack(buildFlashPrompt({ text: notes, lang, style }))
  } catch (err) {
    console.error('inbound: pack generation failed', err)
    if (resend && replyTo) {
      await replyNotice(resend, replyTo, 'We could not process those notes',
        'Something went wrong generating your pack. Please try again, or paste the notes directly in the app.',
        { label: 'Open MeetingFlash', url: `${APP_URL}/app` })
    }
    return NextResponse.json({ ok: true, error: 'generation failed' })
  }

  // Persist exactly like the web flow so the pack shows up in the dashboard.
  let meetingId: string | null = null
  try {
    const subject = typeof data.subject === 'string' ? data.subject.trim() : ''
    const { data: saved } = await admin.from('meetings').insert({
      user_id: profile.id,
      title: pack.title || subject || 'Meeting by email',
      raw_notes: notes,
      pack,
      lang,
      style,
    }).select('id').single()

    meetingId = saved?.id ?? null

    if (meetingId && Array.isArray(pack.tasks) && pack.tasks.length > 0) {
      await admin.from('tasks').insert(pack.tasks.map(t => ({
        user_id: profile.id,
        meeting_id: meetingId,
        text: t.text,
        owner: t.owner || 'Team',
        deadline: t.deadline || null,
        priority: t.priority || 'medium',
        status: 'todo',
      })))
    }

    await admin.rpc('increment_uses', { user_id: profile.id })
  } catch (err) {
    console.error('inbound: save failed', err)
    // Still deliver the pack — losing the email would be worse than losing history.
  }

  if (resend && replyTo) await replyWithPack(resend, replyTo, pack, meetingId)

  return NextResponse.json({ ok: true, meetingId })
}
