'use client'
import { useState, useEffect } from 'react'
import { useRouter, useParams } from 'next/navigation'
import Link from 'next/link'
import { supabase } from '@/lib/supabase'
import styles from './pack.module.css'

interface Task {
  id: string
  text: string
  owner: string
  deadline: string | null
  priority: string
  status: 'todo' | 'in_progress' | 'done'
}

interface Meeting {
  id: string
  title: string
  created_at: string
  lang: string
  style: string
  pack: Record<string, string>
  raw_notes: string
}

const BLOCKS = [
  { id: 'decisions', label: 'Decisions',      color: 'spark'  },
  { id: 'actions',   label: 'Action Items',   color: 'ember'  },
  { id: 'questions', label: 'Open Questions', color: 'fog'    },
  { id: 'risks',     label: 'Risks',          color: 'danger' },
  { id: 'email',     label: 'Follow-up Email',color: 'paper'  },
  { id: 'slack',     label: 'Slack Message',  color: 'paper'  },
  { id: 'agenda',    label: 'Next Agenda',    color: 'spark'  },
]

export default function PackDetail() {
  const router = useRouter()
  const params = useParams()
  const [meeting, setMeeting] = useState<Meeting | null>(null)
  const [loading, setLoading] = useState(true)
  const [copied, setCopied]   = useState<string | null>(null)
  const [tasks, setTasks] = useState<Task[]>([])
  const [shareUrl, setShareUrl] = useState<string | null>(null)
  const [sharing, setSharing]   = useState(false)
  const [showShareMenu, setShowShareMenu] = useState(false)

  useEffect(() => {
    if (!params?.id) return
    async function load() {
      const { data: { session } } = await supabase.auth.getSession()
      if (!session) { router.push('/login'); return }

      const { data } = await supabase
        .from('meetings')
        .select('*')
        .eq('id', params.id)
        .eq('user_id', session.user.id)
        .single()

      if (!data) { router.push('/dashboard'); return }
      setMeeting(data as Meeting)
      const { data: taskData } = await supabase
        .from('tasks')
        .select('*')
        .eq('meeting_id', params.id)
        .order('created_at', { ascending: true })

      setTasks((taskData as Task[]) || [])
      setLoading(false)
    }
    load()
  }, [params.id, router])

    async function updateTaskStatus(taskId: string, status: 'todo' | 'in_progress' | 'done') {
      await supabase
        .from('tasks')
        .update({ status, updated_at: new Date().toISOString() })
        .eq('id', taskId)

      setTasks(prev => prev.map(t => t.id === taskId ? { ...t, status } : t))
    }

    async function generateShareLink() {
      if (!meeting) return
      setSharing(true)

      const token = Math.random().toString(36).slice(2) + Date.now().toString(36)

      await supabase
        .from('meetings')
        .update({ share_token: token })
        .eq('id', meeting.id)

      const url = `${window.location.origin}/share/${token}`
      setShareUrl(url)
      if (navigator?.clipboard) {
        navigator.clipboard.writeText(url)
      }
      setSharing(false)
    }

  function copy(id: string, content: string) {
    if (!navigator.clipboard) return
    navigator.clipboard.writeText(content)
    setCopied(id)
    setTimeout(() => setCopied(null), 2000)
  }

  function exportPDF() {
    window.print()
  }

  function copyAll() {
    if (!meeting) return
    const all = BLOCKS
      .map(b => `${b.label.toUpperCase()}\n${meeting.pack[b.id] || '—'}`)
      .join('\n\n')
    copy('all', all)
  }

  function exportAgenda() {
    if (!meeting) return
    const agenda = meeting.pack['agenda'] || ''
    const title = meeting.title || 'Next Meeting'
    const date = new Date(meeting.created_at).toLocaleDateString('en-GB')

    const content = `NEXT MEETING AGENDA
  Generated from: ${title}
  Date: ${date}

  ${agenda}

  ---
  Generated by MeetingFlash
`
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `agenda-${title.toLowerCase().replace(/\s+/g, '-')}.txt`
    a.click()
    URL.revokeObjectURL(url)
}

  if (loading) return (
    <div className={styles.loading}>
      <div className={styles.loadingGlyph} />
    </div>
  )

  if (!meeting) return null

  return (
    <div className={styles.page}>
      <nav className={styles.nav}>
        <Link href="/dashboard" className={styles.back}>← Dashboard</Link>
        <div className={styles.navRight}>
          <button className={styles.copyAllBtn} onClick={copyAll}>
            {copied === 'all' ? '✓ Copied' : 'Copy all'}
          </button>
          <button className={styles.pdfBtn} onClick={exportPDF}>
            Export PDF
          </button>
        </div>
        <div className={styles.shareWrap}>
          <button
            className={styles.shareBtn}
            onClick={async () => {
              if (!shareUrl) await generateShareLink()
              setShowShareMenu(prev => !prev)
            }}
            disabled={sharing}
          >
            {sharing ? 'Generating…' : 'Share'}
          </button>

          {showShareMenu && shareUrl && (
            <div className={styles.shareMenu}>
              <button
                className={styles.shareMenuItem}
                onClick={() => {
                  navigator.clipboard.writeText(shareUrl)
                  setShowShareMenu(false)
                }}
              >
                <span>🔗</span> Copy link
              </button>
              
              <a
                className={styles.shareMenuItem}
                href={`mailto:?subject=${encodeURIComponent(meeting?.title || 'Meeting Pack')}&body=${encodeURIComponent(`Here is the meeting Execution Pack:\n\n${shareUrl}`)}`}
                onClick={() => setShowShareMenu(false)}
              >
                <span>✉️</span> Send by email
              </a>
              
              <a
                className={styles.shareMenuItem}
                href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(`Meeting recap: ${meeting?.title}`)}&url=${encodeURIComponent(shareUrl)}`}
                target="_blank"
                rel="noopener noreferrer"
                onClick={() => setShowShareMenu(false)}
              >
                <span>𝕏</span> Share on X
              </a>
            </div>
          )}
        </div>
      </nav>

      <div className={styles.content}>
        <div className={styles.header}>
          <div className={styles.headerMeta}>
            <span className={styles.date}>
              {new Date(meeting.created_at).toLocaleDateString('en-GB', {
                weekday: 'long', day: 'numeric', month: 'long', year: 'numeric'
              })}
            </span>
            <span className={styles.metaDot}>·</span>
            <span className={styles.lang}>{meeting.lang}</span>
            <span className={styles.metaDot}>·</span>
            <span className={styles.style}>{meeting.style}</span>
          </div>
          <h1 className={styles.title}>{meeting.title}</h1>
        </div>

        <div className={styles.blocks}>
          {BLOCKS.map((block, i) => (
            <div
              key={block.id}
              className={`${styles.block} ${styles[`block_${block.color}`]}`}
              style={{ animationDelay: `${i * 0.06}s` }}
            >
              <div className={styles.blockHead}>
                <div className={styles.blockType}>
                  <div className={`${styles.blockDot} ${styles[`dot_${block.color}`]}`} />
                  <span className={`${styles.blockLabel} ${styles[`label_${block.color}`]}`}>
                    {block.label}
                  </span>
                </div>
                {block.id === 'agenda' ? (
                  <div style={{ display:'flex', gap:6 }}>
                    <button
                      className={`${styles.cpBtn} ${copied === block.id ? styles.cpDone : ''}`}
                      onClick={() => copy(block.id, meeting.pack[block.id] || '—')}
                    >
                      {copied === block.id ? '✓' : 'Copy'}
                    </button>
                    <button className={styles.cpBtn} onClick={exportAgenda}>
                      Export
                    </button>
                  </div>
                ) : (
                  <button
                    className={`${styles.cpBtn} ${copied === block.id ? styles.cpDone : ''}`}
                    onClick={() => copy(block.id, meeting.pack[block.id] || '—')}
                  >
                    {copied === block.id ? '✓' : 'Copy'}
                  </button>
                )}
              </div>
              <div className={styles.blockContent}>
                  : meeting.pack?.[block.id] ?? '—'
              </div>
            </div>
          ))}
        </div>

        {tasks.length > 0 && (
            <div className={styles.taskTracker}>
                <div className={styles.taskTrackerHeader}>
                <div className={styles.taskTrackerTitle}>
                    <span className={styles.taskTrackerTitleSerif}>Task</span> Tracker
                </div>
                <div className={styles.taskStats}>
                    <span className={styles.taskStat}>
                    {tasks.filter(t => t.status === 'done').length}/{tasks.length} done
                    </span>
                </div>
                </div>

                <div className={styles.taskProgress}>
                <div
                    className={styles.taskProgressBar}
                    style={{
                    width: `${tasks.length > 0
                        ? (tasks.filter(t => t.status === 'done').length / tasks.length) * 100
                        : 0}%`
                    }}
                />
                </div>

                <div className={styles.taskList}>
                {tasks.map(task => (
                    <div
                    key={task.id}
                    className={`${styles.taskRow} ${styles[`task_${task.status}`]}`}
                    >
                    <div className={styles.taskLeft}>
                        <div className={styles.taskText}>{task.text}</div>
                        <div className={styles.taskMeta}>
                        {task.owner && (
                            <span className={styles.taskOwner}>{task.owner}</span>
                        )}
                        {task.deadline && (
                            <>
                            <span className={styles.taskMetaDot}>·</span>
                            <span className={styles.taskDeadline}>{task.deadline}</span>
                            </>
                        )}
                        <span className={styles.taskMetaDot}>·</span>
                        <span className={`${styles.taskPriority} ${styles[`priority_${task.priority}`]}`}>
                            {task.priority}
                        </span>
                        </div>
                    </div>
                    <div className={styles.taskActions}>
                        {(['todo', 'in_progress', 'done'] as const).map(s => (
                        <button
                            key={s}
                            className={`${styles.statusBtn} ${task.status === s ? styles.statusBtnActive : ''} ${styles[`statusBtn_${s}`]}`}
                            onClick={() => updateTaskStatus(task.id, s)}
                        >
                            {s === 'todo' ? 'Todo' : s === 'in_progress' ? 'In progress' : 'Done'}
                        </button>
                        ))}
                    </div>
                    </div>
                ))}
                </div>
            </div>
          )
        }
        <details className={styles.rawNotes}>
          <summary className={styles.rawNotesSummary}>View original transcript</summary>
          <div className={styles.rawNotesContent}>{meeting.raw_notes}</div>
        </details>
      </div>
    </div>
  )
}